version: "3" # keep deprecated version attribute for compatibility with old docker compose versions

networks:
  computer-management-net:

services:
  computer-management:
    build: .
    networks:
      - computer-management-net
    ports:
      - 5000:5000
    command: --host 0.0.0.0 --port 5000 --notification-service "http://admin-notification:8080"

  admin-notification:
    image: greenbone/exercise-admin-notification:latest
    networks:
      - computer-management-net
    ports:
      - 8080:8080
